### ISSUE TITLE
Multiple bossbar

### ISSUE THREAD

**Issue by matahombres** [nkomarn/harbor#58] opened 2020-07-06 16:04 UTC
![image](https://user-images.githubusercontent.com/17030845/86614189-e9740480-bfb2-11ea-89a2-8cc8441e99f5.png)

Server: paperspigot 1.15.2 - build 318
Version: 1.6.2 beta 6

**Comment by nkomarn** [comment] 2020-07-08 13:52
I'll look into the cause of this.

**Comment by nkomarn** [comment] 2020-08-20 00:26
This bug should be fixed as of Harbor 1.6.2 beta 7. Give it a try and re-open this issue if you continue to experience the problem: https://github.com/nkomarn/Harbor/releases.

**Closed as completed by nkomarn** 2020-08-20 00:26 UTC
Labels: bug
