### ISSUE TITLE
Weather change error. 

### ISSUE THREAD

**Issue by Sundheden** [nkomarn/harbor#17] opened 2019-06-09 09:21 UTC
**Version:** 
CraftBukkit version git-Spigot-baafee9-17543ec (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)

**Not clearing weather when sleeping.**

**Console error output:**
`[09:02:50] [Server thread/INFO]: X is now sleeping (1/1, 0 more needed to skip).
[09:02:52] [Timer-53/WARN]: Exception in thread "Timer-53"
[09:02:52] [Timer-53/WARN]: java.lang.IllegalStateException: WeatherChangeEvent cannot be triggered asynchronously from another thread.
[09:02:52] [Timer-53/WARN]:     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[09:02:52] [Timer-53/WARN]:     at net.minecraft.server.v1_14_R1.WorldData.setStorm(WorldData.java:556)
[09:02:52] [Timer-53/WARN]:     at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.setStorm(CraftWorld.java:1122)
[09:02:52] [Timer-53/WARN]:     at mykyta.Harbor.Util$1.run(Util.java:208)
[09:02:52] [Timer-53/WARN]:     at java.util.TimerThread.mainLoop(Timer.java:555)
[09:02:52] [Timer-53/WARN]:     at java.util.TimerThread.run(Timer.java:505)`

**Comment by nkomarn** [comment] 2019-06-10 22:32
WIll look into this!

**Comment by nkomarn** [comment] 2019-06-21 16:29
That is apparently caused by a Spigot API change in 1.14. I have now fixed it and the patch will be part of the next release of Harbor (1.5.1).

**Closed as completed by nkomarn** 2019-06-21 16:29 UTC
