### ISSUE TITLE
Error when just one player is online and sleeping

### ISSUE THREAD

**Issue by iperrealistico** [nkomarn/harbor#21] opened 2019-06-29 12:50 UTC
As far as i know the plugin seems to be working fine.. i had some issues but they are now fixed. But when a player is alone on the server and tries to sleep, an error appears in console.

[14:47:47 INFO]: jlrcraft is now sleeping (0 needed to skip the night).
[14:47:47 WARN]: Exception in thread "Timer-6" java.lang.IllegalStateException: WeatherChangeEvent may only be triggered synchronously.
[14:47:47 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:524)
[14:47:47 WARN]:        at net.minecraft.server.v1_14_R1.WorldData.setStorm(WorldData.java:556)
[14:47:47 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.setStorm(CraftWorld.java:1207)
[14:47:47 WARN]:        at mykyta.Harbor.Util$1.run(Util.java:208)
[14:47:47 WARN]:        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[14:47:47 WARN]:        at java.base/java.util.TimerThread.run(Timer.java:506)

Running on Paper 97

**Comment by nkomarn** [comment] 2019-06-29 18:03
Duplicate of #17 and will be fixed in the next update.

**Closed as completed by nkomarn** 2019-06-29 18:03 UTC
